### ISSUE TITLE
Module fails to load in sopel

### ISSUE THREAD

**Issue by Strykar** [ktwilson86/sopel-darksky#1]
`Sopel 6.6.9 (running on python 3.6.7)`

```
strykar@phreedom:~/.sopel/logs$ tail -f stdio.log 

Error loading darksky: name 'reload' is not defined (../../../../../../../../../home/strykar/.sopel/modules/darksky.py:19)


Registered 47 modules,
1 modules failed to load
```
How can I test this in a terminal?

**Comment by ktwilson86** [comment]
This looks related to the python version, I originally tested this in python 2.7 but the reload command has been moved to the importlib module for python 3.4 and above. If the line 
`reload(sys)`
is changed to
```
import importlib
importlib.reload(sys)
```

that should solve the issue. I will test with 3.6 and see if it works.

**Comment by ktwilson86** [comment]
Fixed this and a couple other bugs, module should work fine in 3.6 now.
